// <auto-generated />
using System;
using Bernal.ERP.ControleInventario.Infra;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Bernal.ERP.ControleInventario.Infra.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220330193046_V1")]
    partial class V1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Bernal.ERP.ControleInventario.Dominio.Entidades.Contagem", b =>
                {
                    b.Property<int>("ContagemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tipo_de_contagem_id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Equipe")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("equipe");

                    b.Property<int>("InventarioItemId")
                        .HasColumnType("integer")
                        .HasColumnName("inventario_item_id");

                    b.Property<string>("Sessao")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("sessao");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("ContagemId");

                    b.HasIndex("InventarioItemId");

                    b.ToTable("tipo_de_contagem");
                });

            modelBuilder.Entity("Bernal.ERP.ControleInventario.Dominio.Entidades.Inventario", b =>
                {
                    b.Property<int>("InventarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("inventario_id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime?>("ExcluidoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("excluido_em");

                    b.Property<DateTime?>("FinalizadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("finalizado_em");

                    b.Property<DateTime>("IniciadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("iniciado_em");

                    b.HasKey("InventarioId");

                    b.ToTable("inventarios");
                });

            modelBuilder.Entity("Bernal.ERP.ControleInventario.Dominio.Entidades.InventarioDispositivo", b =>
                {
                    b.Property<int>("InventarioDispositivoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("inventario_dispositivo_id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime?>("ExcluidoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("excluido_em");

                    b.Property<DateTime?>("FinalizadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("finalizado_em");

                    b.Property<DateTime>("IniciadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("iniciado_em");

                    b.Property<int>("InventarioId")
                        .HasColumnType("integer")
                        .HasColumnName("inventario_id");

                    b.Property<string>("NumeroDeSerie")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("numero_de_serie");

                    b.Property<string>("ResponsavelPelaContagem")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reponsavel_pela_contagem");

                    b.HasKey("InventarioDispositivoId");

                    b.HasIndex("InventarioId");

                    b.ToTable("inventario_dispositivos");
                });

            modelBuilder.Entity("Bernal.ERP.ControleInventario.Dominio.Entidades.InventarioItem", b =>
                {
                    b.Property<int>("InventarioItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("inventario_item_id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("Embalagem")
                        .HasColumnType("integer")
                        .HasColumnName("embalagem");

                    b.Property<DateTime?>("ExcluidoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("excluido_em");

                    b.Property<decimal>("Icms")
                        .HasColumnType("numeric")
                        .HasColumnName("icms");

                    b.Property<int>("InventarioId")
                        .HasColumnType("integer")
                        .HasColumnName("inventario_id");

                    b.Property<decimal>("Precocustoembalagem")
                        .HasColumnType("numeric")
                        .HasColumnName("preco_custo_embalagem");

                    b.Property<decimal>("Precofinal")
                        .HasColumnType("numeric")
                        .HasColumnName("preco_final");

                    b.Property<string>("ProdutoCodigo")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("produto_codigo");

                    b.Property<string>("ProdutoNome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("produto_nome");

                    b.Property<decimal>("QuantidadeDeEmbalagem")
                        .HasColumnType("numeric")
                        .HasColumnName("quantidade_embalagem");

                    b.Property<decimal>("Transporte")
                        .HasColumnType("numeric")
                        .HasColumnName("transporte");

                    b.HasKey("InventarioItemId");

                    b.HasIndex("InventarioId");

                    b.ToTable("inventario_itens");
                });

            modelBuilder.Entity("Bernal.ERP.ControleInventario.Dominio.Entidades.Contagem", b =>
                {
                    b.HasOne("Bernal.ERP.ControleInventario.Dominio.Entidades.InventarioItem", "InventarioItem")
                        .WithMany("Contagem")
                        .HasForeignKey("InventarioItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventarioItem");
                });

            modelBuilder.Entity("Bernal.ERP.ControleInventario.Dominio.Entidades.InventarioDispositivo", b =>
                {
                    b.HasOne("Bernal.ERP.ControleInventario.Dominio.Entidades.Inventario", "Inventario")
                        .WithMany("InventarioDispositivos")
                        .HasForeignKey("InventarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventario");
                });

            modelBuilder.Entity("Bernal.ERP.ControleInventario.Dominio.Entidades.InventarioItem", b =>
                {
                    b.HasOne("Bernal.ERP.ControleInventario.Dominio.Entidades.Inventario", "Inventario")
                        .WithMany("InventarioItems")
                        .HasForeignKey("InventarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventario");
                });

            modelBuilder.Entity("Bernal.ERP.ControleInventario.Dominio.Entidades.Inventario", b =>
                {
                    b.Navigation("InventarioDispositivos");

                    b.Navigation("InventarioItems");
                });

            modelBuilder.Entity("Bernal.ERP.ControleInventario.Dominio.Entidades.InventarioItem", b =>
                {
                    b.Navigation("Contagem");
                });
#pragma warning restore 612, 618
        }
    }
}
